### ISSUE TITLE
add `ember-simple-auth` to app

### ISSUE THREAD

**Issue by lifeart** [lifeart/demo-ember-vite#28]
We need to add `ember-simple-auth` app.

* App should have lazy-loaded private `profile` route.
* App should have `login` route with `Login` component.
* App should have `logout` route to log-out user (if route visited) and redirect it to `main` route.

**Comment by kaermorchen** [comment]
This looks not hard. I get it.

**Comment by lifeart** [comment]
fixed by https://github.com/lifeart/demo-ember-vite/pull/32
