### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by kaermorchen** [lifeart/demo-ember-vite#36]
Right now, all project files are created manually. It is not friendly. We need a `cli` tool. This is not a nearby issue; we need to create it when all file structures and concepts will be stable. But some suggestions now can reduce refactoring in the future.

The goal is to reduce amount of manual work for repeated actions like to generate a new route or component (as @lifeart have suggested in #30)

My thought:
- the commands should be similar ember-cli
- the project file structure shouldn't be hardcoded
- be as simple as possible, but has a modular structure, and anyone can simply extend logic, override settings and create new commands in the project.
- should be out of the box. It can be an external package, (may be in the monorepo with this demo), it allows to execute it from `node_modules/bin/` or `npx`

Any other ideas?

**Comment by lifeart** [comment]
agree, blueprints (for now) could be located in `/blueprints`, and likely should be way simplier, comparing to `ember-cli` one's.

Sample generators: https://dev.to/mbarzeev/creating-a-react-component-generator-20l, https://yeoman.io/

I like simplicity of https://plopjs.com/, but we could explore more if needed.

**Comment by lifeart** [comment]
implemented in https://github.com/lifeart/demo-ember-vite/pull/41
